### ISSUE TITLE
Latest-tag failing the action

### ISSUE THREAD

**Issue by drekka** [release-kit/semver#34]
Hi. Trying to use the action for the first time. When I add `source: latest-tag` to my workflow it crashes out. Here's my action:

```yaml
    steps:
      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v2
        with:
          source: latest-tag
          pattern: '^Release-(.*)$' # ^v?(.*)$ by default
```

And here's the error I get:

```
/Users/runner/work/_actions/release-kit/semver/v2/dist/index.js:6451
		error = new Error(message);
		        ^

Error: Command failed with exit code 128: git rev-list --tags --max-count=1
fatal: not a git repository (or any of the parent directories): .git
    at makeError$1 (/Users/runner/work/_actions/release-kit/semver/v2/dist/index.js:6451:11)
    at handlePromise (/Users/runner/work/_actions/release-kit/semver/v2/dist/index.js:7410:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 128: git rev-list --tags --max-count=1',
  command: 'git rev-list --tags --max-count=1',
  escapedCommand: 'git rev-list --tags "--max-count=1"',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: not a git repository (or any of the parent directories): .git',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
```

anything I might have done wrong?

Note that it works if I remove the `source:` line. But means the tag has to be on the last commit.
